### ISSUE TITLE
Breaks with pytest 3.7.0

### ISSUE THREAD

**Issue by romanlevin** [tholo/pytest-flake8#52] opened 2018-08-01 11:46 UTC
```
_____________________________________________________________________________________________________________ ERROR collecting  ______________________________________________________________________________________________________________
/home/vagrant/.pyenv/versions/3.6.5/envs/turbo/lib/python3.6/site-packages/_pytest/runner.py:201: in __init__
    self.result = func()
/home/vagrant/.pyenv/versions/3.6.5/envs/turbo/lib/python3.6/site-packages/_pytest/runner.py:261: in <lambda>
    call = CallInfo(lambda: list(collector.collect()), "collect")
/home/vagrant/.pyenv/versions/3.6.5/envs/turbo/lib/python3.6/site-packages/_pytest/main.py:475: in collect
    for x in self._collect(arg):
/home/vagrant/.pyenv/versions/3.6.5/envs/turbo/lib/python3.6/site-packages/_pytest/main.py:505: in _collect
    col = root._collectfile(pkginit)
E   AttributeError: 'Flake8Item' object has no attribute '_collectfile'
```

**Comment by jacquerie** [comment] 2018-08-01 11:49
Duplicate of https://github.com/tholo/pytest-flake8/issues/51.

**Closed by jacquerie** 2018-08-01 11:49 UTC
