### ISSUE TITLE
Last update breaks CI pipelines

### ISSUE THREAD

**Issue by EtimoOscarNylander** [tholo/pytest-flake8#39] opened 2017-10-27 09:17 UTC
I'm posting this mostly as an FYI for the people who had their CI pipelines starting to fail related to this package, with a message that looks sort of like this:
```
/usr/local/lib/python3.6/site-packages/pytest_flake8.py:115: in runtest
    self.statistics)
/usr/local/lib/python3.6/site-packages/py/_io/capture.py:150: in call
    res = func(*args, **kwargs)
/usr/local/lib/python3.6/site-packages/pytest_flake8.py:180: in check_file
    app.find_plugins()
/usr/local/lib/python3.6/site-packages/flake8/main/application.py:176: in find_plugins
    self.prelim_opts.config,
E   AttributeError: 'NoneType' object has no attribute 'config'
```

I'm not sure how, but it appears that the code for version 0.8.1 on pip may have changed, causing incompatibility issues. The solution to this issue is to update the version of this package and possibly also pytest:

requirements.txt
```
- pytest==3.0.7
- pytest-flake8==0.8.1
+ pytest==3.2.3
+ pytest-flake8==0.9.1
```

Hopefully this shows up in google for people who gets this issue so they can solve it quickly 👍

**Comment by jacquerie** [comment] 2017-10-27 09:21
Hi @EtimoOscarNylander, thanks for the report.

This is actually a duplicate of https://github.com/tholo/pytest-flake8/issues/34, and indeed the solution is to upgrade `pytest-flake8` to at least `0.9.0`.

**Closed by jacquerie** 2017-10-27 09:21 UTC
